Feature/#95 coloring by temporal field leads to weird results
chartshq/muze pull request #109
Opened 2019-01-23 15:13 UTC by rousan

2019-01-24 12:57 UTC, adotg requested changes

2019-01-24 12:57 UTC, adotg commented on packages/muze-legend/src/legend/discrete-legend.js
> +            if (type === FieldType.MEASURE) {
If this is a discrete legend then it will never get created if a measure is assigned to color

2019-01-24 12:57 UTC, adotg commented on packages/visual-unit/src/listener-map.js
> +            Object.entries(context.fields()).forEach(([type, [field]]) => {
Doesn't need to be inside listeners. Executes every time listeners are fired.

2019-01-24 12:57 UTC, adotg commented on packages/visual-unit/src/listener-map.js
> +            if (dataModel && axesObj) {
Remove condition checking

2019-01-24 12:57 UTC, adotg commented on packages/visual-unit/src/listener-map.js
> +                Object.entries(allFields).forEach(([type, field]) => {
Should not be cognizant of VariableType

2019-01-25 13:16 UTC, rousan commented
The diff for coloring by temporal field as follows:
```
.rows(['Acceleration'])
.columns(['Origin'])
.color("Year")
```


The previous Image:
![image](https://user-images.githubusercontent.com/12519292/51748089-5a7e6f80-20d1-11e9-88cd-e2c4d300c8b4.png)

The current Image:
![image](https://user-images.githubusercontent.com/12519292/51748100-6407d780-20d1-11e9-89eb-b52d03c10bdf.png)

The current Image with diff annotations:
![image](https://user-images.githubusercontent.com/12519292/51748133-7eda4c00-20d1-11e9-9ec8-a12e4e6320f0.png)

The Diff:
![image](https://user-images.githubusercontent.com/12519292/51748156-88fc4a80-20d1-11e9-88f0-af8d3b1ca6cb.png)

2019-01-28 11:18 UTC, merged